### ISSUE TITLE
Can not create a tax code 

### ISSUE THREAD

**Issue by coxced** [blueseerERP/blueseer#105]
Can not create a tax code. Says Record not added!

Video Attached!

Thanks, Cedric

https://user-images.githubusercontent.com/123996361/223200918-11c514c3-d8bf-42e7-9449-f427adba2107.mp4

**Comment by vaughnte** [comment]
This is a bug with the MySQL version .   Data.log file details:
Mar 06, 2023 9:19:05 PM bsmf.MainFrame bslog
SEVERE: null
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect date value: '' for column 'tax_crtdate' 

I will update the blueseer.jar with a patch asap.

**Comment by vaughnte** [comment]
This has been patched and a new jar file provided in the 6.4 release.   Download the blueseer.jaronly.zip file, extract the blueseer.jar file from the zip, and overwrite file at blueseer/dist/blueseer.jar.   Then restart the app.  The link is here:  https://github.com/blueseerERP/blueseer/releases/download/v6.4/blueseer.jaronly.zip .

**Comment by coxced** [comment]
Thanks, that fixed it!
