### ISSUE TITLE
a  version for startups  and smaller businesses

### ISSUE THREAD

**Issue by fadi123go** [blueseerERP/blueseer#110]
I find your app targeted at manufacturing enerprises. Smaller businesses only need basic accounting features, ability to create invoices , basic crm and inventory management .They do not need all these unnecessary fields , all these serial codes. They usually deal with a dozen of products and sell to less than a hundred customers. They may need basic shipping features .Addressing this issue , if you like the idea off course, will take a long time . Blueseer should come in two versions enterprise , the current one , and startup, the one I propose. It is up to you if you have the time.

**Comment by fadi123go** [comment]
But is there a way to hide those fields, like an edit window link in each window and when you click it , the same window shows but with check boxes beside optional fields . Uncheck what you want to hide. Can you add a major feature like this . I will be able to scale it down or up to my liking. Easily editable forms .

**Comment by vaughnte** [comment]
unfortuanately no...there is no way to hide the fields.   What you are proposing would require a complete refactor of the UI from scratch...and that is not likely to happen.

**Comment by fadi123go** [comment]
Thanks a lot Mr Vaughn.
