### ISSUE TITLE
cannot add a new expense (maintenance)

### ISSUE THREAD

**Issue by SteBakhita** [blueseerERP/blueseer#116]
Hello everyone,
When I want to reproduce the example from Expense Transactions and Expense Accounting tutorial, I get an error that recording failed, when I look at the log, I found this error below:
Invalid integer value: '' for column 'ap_batch' at line 1
I tried changing the sql mode but got the same error, i tried several times with a new instance but got the same error; I'm new to blueseerErp trying to figure out what I'm doing wrong! please can you help me thank you

**Comment by vaughnte** [comment]
Hello,

Currently the ap_batch field (for the sqlite version) has a default value of ''  ...and should have a default value of '0'.   I will put in a patch fix for this today.  WIth that said, however, I am able to complete the Expense Transaction without an issue....even though the default value is ''.   The sqlite version ignores the 'empty' default value assigned during the transaction...at least for me.   Please send the blueseer/data/app.log file to support@blueseer.com.   Also...send what version you are on.   I am curious as to the stacktrace of this error.     
Note:  the corrected field type should be :  "ap_batch" int(11) COLLATE NOCASE DEFAULT '0'   ...and not DEFAULT ''.    You can adjust the sql field definition in sqlite....or wait for the patch and download the package again.

**Comment by SteBakhita** [comment]
Thanks for your answer, but when I use the new syntax you gave me 'ap_batch" int(11) COLLATE NOCASE DEFAULT '0'' in the schema it breaks the mysql.bat script with this error: ERROR 1273 ( HY000) at line 135: Unknown collation: 'NOCASE'
when i try to change directly in Mysql Workbench tool it's the same first error.
i use mysql 8.0.33 and blueseer 6.5.14

**Comment by vaughnte** [comment]
I see the issue.   I have updated the patch.   I will need you to do two things : 
1)  download the blueseer.jar file from the below link and replace into blueseer/dist/ folder...overwriting the old.
2)  using mysql...look and see if you have a mysql field at the bottom of ap_mstr table called 'ap_subtype'.  If you do not, then add this field using the following syntax:  alter table ap_mstr add column ap_subtype varchar(20) default '';
Restart the app and try it again.
link to jar file:  https://github.com/blueseerERP/blueseer/releases/download/v6.5/blueseer.jaronly.zip

**Comment by SteBakhita** [comment]
thanks it works now !

**Comment by vaughnte** [comment]
sounds good...I'll close the ticket.
