### ISSUE TITLE
API cannot start

### ISSUE THREAD

**Issue by bmp02050** [blueseerERP/blueseer#118]
running this in the C:\blueseer director: 
java -cp “.;dist\*” utilities.apiServer

The java file cannot be found. Is the API still available in this? If so, is there updated documentation on this?

**Comment by vaughnte** [comment]
you're missing the '/' after dist.   Here's an example:
c:/blueseer/jre17/bin/java -cp ".;dist/*" utilities.apiServer
Also...if you do not use the embedded java executable (as I did in the example)...you will need to ensure that you are using Java 17 or higher.

**Comment by bmp02050** [comment]
Excellent! Thank you. Is there any authentication on the API? Any plans to
expand on the API aspect of it?

**Comment by vaughnte** [comment]
There is no authentication required on the APIs...as it was designed for internal network usage only.   There are only a few 'standard' APIs in the package....but I will entertain enhancements if they are beneficial overall to the application.   The API service...utilities.apiServer....also drives the cron entries and systems jobs.   (The documentation is woefully behind on this).  With regards to work order API validation, the API does have 'some' validation...(item must be in item master, work order number must exist and must be open, and operation of routing must be a valid operation).   If you have any issues with the APIs....shoot an email to support@blueseer.com ....and I'll take a look at it.

**Comment by bmp02050** [comment]
Thank you!
