### ISSUE TITLE
PO maintenance returns null for description field when retrieving previously assign items to purchase order

### ISSUE THREAD

**Issue by vaughnte** [blueseerERP/blueseer#13]
PO maintenance returns null for description field when retrieving previously assign items to purchase order.   The sql query to retrieve the record left outer joins the item master table, but will return null if the item in question is a miscellaneous non-inventory item assigned to the purchase order.

**Comment by vaughnte** [comment]
Added ifNull check for left outer join field.

**Comment by vaughnte** [comment]
retracting the previous ifNull addition.   The sql call logic assumed inventory items but when non-inventory items were added, the it_desc was non-existent...returning NULL for left outer join.   Removed the left out join all together...and inserted a new pod_desc field to capture the description for non-inventory items as well as inventoried items.

**Comment by vaughnte** [comment]
This correction is included with patch version 6.0.1

**Comment by vaughnte** [comment]
This correction is included with patch version 6.0.1

**Comment by gjgrosso** [comment]
I unsubscribed but still get these so drop me from your distribution list


GJG
