### ISSUE TITLE
Demo Version of Blueseer

### ISSUE THREAD

**Issue by theonewolf** [blueseerERP/blueseer#140]
Documentation mentions a "Demo Installation" version of Blueseer.  How do I get that?  Is there a sqlite DB file?  Some admin command?  Or some special installer?

**Comment by vaughnte** [comment]
It is referring to the sqlite version of BlueSeer.    It can be downloaded at the following link:  https://github.com/blueseerERP/blueseer/releases/download/v7.0/blueseer.sqlite.win.v7.0.exe

**Comment by theonewolf** [comment]
Oh thanks @vaughnte.  I have that, will check for dummy data in it as according to the PDF documentation.

Thank you.

**Comment by vaughnte** [comment]
if you're looking for test data...click on Admin --> Master Data Import ....then click the 'Test Data Load' button and follow the prompts.   This will load the app with test (dummy) data.
