### ISSUE TITLE
code navigation entry stops working

### ISSUE THREAD

**Issue by matthewlongfield** [blueseerERP/blueseer#143]
After selecting certain items from the standard menus (EDI, Admin, ..) the direct code entry field no longer works (no carat when clicking it, cannot type in a code). It also stops after certain other selections, particularly after lookup operations.

Here's how it can be reproduced

enter eddm (it's still working)
use the magnifying glass to lookup all the available records in 'Code' field, select one, like 850xml (it's now deactive)

added a screenshot highlighting the code entry field
![code navigate field](https://github.com/user-attachments/assets/526ae3c9-ae54-4e2d-a45b-2e51576a3760)

**Comment by vaughnte** [comment]
Matt...check the c:\blueseer\data directory for an app.log file.   If you have one...send it to support@blueseer.com.  My guess is a bad record is throwing a JDBC sql exeception...and freezing the main event thread...causing screen freezes.    Restarting the app will clear it up...but it'll happen again with same navigation until we determine the problem.

**Comment by vaughnte** [comment]
This was a result of modifications to the main menu bar during release of version 7.   This has been patched with patch release 7.0.19.   All downloadables have been refreshed with the updated patch.

**Comment by matthewlongfield** [comment]
I can verify that the direct code entry field no longer refuses to take input after scenario eddm->magnifying-glass-lookup
I didn't try a fresh install of 7.0.19, but after overwriting bsmf.jar & blueseer.jar it now operates as expected

**Comment by matthewlongfield** [comment]
Closing issue. Thanks!
