### ISSUE TITLE
misc production record can not been closed

### ISSUE THREAD

**Issue by smurfjack** [blueseerERP/blueseer#150]
i enter a misc production task,and use production entry to satisfy the scheduled qty. the schedued production task will not been set to closed automatically. and there is no way to close it.I tried to enter the last operation(auto backflush) qty. it make no sense. and i enterd other 3 operations last,make no sense too.

**Comment by vaughnte** [comment]
You need to make sure you are using the 'Production Entry By Plan' menu to post production if you want to close a Plan Order created from Misc Plan Maintenance and scheduled via the Scheduler.   The autobackflush must be set on the last operation in the routing as well.   If you scan the last operation for the quantity that completes the scheduled quantity, then it will indeed close.   You can scan in any order of operation...for example 30,10,20,40...(not sure why you would do this) but once the final operation is scanned, the ticket/plan number will close.    Check and see if you have a c:\blueseer\data\app.log file....if so....send it to support@blueseer.com along with your version number and your langpack used....we will take a look at your issue.
