### ISSUE TITLE
Cannot use same routing code for multiple operations

### ISSUE THREAD

**Issue by binief** [blueseerERP/blueseer#20]
Cannot use same routing code for multiple operations
It says record already exists

**Comment by vaughnte** [comment]
This is a bug in routing maintenance class and subclass.   It is not allowing more than one operation to be created per routing master ID.   This bug has been corrected...and will be provided in download release 6.0.3.

**Comment by vaughnte** [comment]
I have uploaded the 6.0.3 release download files.   Since this is a core patch, download the blueseer.jaronly.zip file.   There is instructions inside to apply the patch.

**Comment by vaughnte** [comment]
Both windows and linux 6.0.3 releases have been uploaded.  Closing

**Comment by binief** [comment]
![image](https://user-images.githubusercontent.com/26696063/148717261-62651632-6eca-4bf2-890f-8ca147102d1d.png)

Within item maintenance, routing dropdown is showing duplicate routing code
