### ISSUE TITLE
Uploading Customer Pricing

### ISSUE THREAD

**Issue by jsuttonBRC** [blueseerERP/blueseer#41]
When importing a customer price list, the data loads, and shows the record is created.
However it does not show up when creating an order or on the customer price maintenance screen.
(for example, once it been created I can no longer add a price for the EA unit of measurement.  However, change it to gallons and it displays correctly in the applied textarea.)
![pricing snip](https://user-images.githubusercontent.com/94138983/159612604-c52c666a-0837-48d3-bdb7-dff5a8b75870.jpg)

**Comment by vaughnte** [comment]
Can you confirm what version you are using?   This issue may have been addressed with the previous reported issue #40.   The version can be seen at the top of the menu bar.
