### ISSUE TITLE
Download method for patches from github into application instance

### ISSUE THREAD

**Issue by vaughnte** [blueseerERP/blueseer#50]
Download mechanism for patches from github.   Routine would search github blueseer repository for patches of instance version, download patch zip, and extract, deploy zip contents into working path.   These would be standard patches to begin.   A potential option would be to provide key for 'custom' non-standard downloads that are specific to enduser instance (troubleshooting efforts, etc).

**Comment by vaughnte** [comment]
this is scheduled for release with 6.1.8

**Comment by vaughnte** [comment]
6.1.8 released

**Comment by dhroovprasad** [comment]
Login details for Blueseer panel ?

![image](https://user-images.githubusercontent.com/104079388/164241595-267106d5-8d93-4d08-8103-4e9ff07e9448.png)

**Comment by vaughnte** [comment]
username and password are both 'admin'

**Comment by dhroovprasad** [comment]
Can you provide a manual to learn the  software for inventory management.




Best Regards-

Dhroov Prasad
