### ISSUE TITLE
A weighbridge module

### ISSUE THREAD

**Issue by fadi123go** [blueseerERP/blueseer#59]
Could you create weighbridge component for blueseer . The company I work in receives input material in weight using a truck scale. It would be great if your erp can connect with weighbridges and capture weights.

**Comment by vaughnte** [comment]
This would be more of a customization effort...and not a generic enhancement.    It would be highly dependent on the weighbridge vendor and api offerings...where I assume they are all different.    If the weighbridge does have legitimate apis ...you could theoretically contract a developer to integrate the weighscale apis into the Receiver class of BlueSeer (or simply inventory movement...depending on the objective).   But this would be a customization instance/effort by the enduser...and not a good fit for a generic enhancement of the BlueSeer app in general.   I do not know that much about the use case scenarios of weighbridges...so if anyone sees a generic enhancement opportunity...i.e....the apis are standard across the weighbridge vendor products....then I would be willing to reconsider.

**Comment by fadi123go** [comment]
Thanks a lot Mr Vaughn. I have another question : where the data is saved and how to keep it when upgrading from one version to another ?

**Comment by vaughnte** [comment]
if you're using the sqlite version...the data is stored in c:\blueseer\data\bsdb.db.    This is a simple file type database....you can copy this over to another folder or drive or USB stick any time you feel a need to back it up.      For upgrades, you can simply copy this file to a temp and restore after the upgrade...(assuming the upgrade doesn't have database schema changes).    There is a utility for getting the latest patch for any version that you're own however.   See System Control.   Most patches are embedded in the bluseer.jar file that can be downloaded and copied over c:\blueseer\dist\blueseer.jar.   If you have further questions or concerns on this....send an email to support listed on the blueseer.com contact page.

**Comment by vaughnte** [comment]
closing this...too custom a request for generic enhancement.
