### ISSUE TITLE
Config File is Missing when attempting to Compile

### ISSUE THREAD

**Issue by iswaryalakshmim** [blueseerERP/blueseer#64]
![Screenshot from 2022-07-01 17-28-32](https://user-images.githubusercontent.com/108528009/176890550-c0792b42-e49b-4140-ac44-b6d91169b4bd.png)
![Screenshot from 2022-07-01 17-47-12](https://user-images.githubusercontent.com/108528009/176892772-186e8bbe-2f50-44cb-9f1a-218e5c6f2d75.png)

Hi Sir/Mam,

I choose a blueseer project then deploy the project, but i received the error message - Config File is missing ..

**https://www.blueseer.com/compile.html**

The above link was used to how to deploy the project, but i am unable to deploy the project because config file is missing error displayed. Now what i do , how to configuration the file and which file solving the error to be added. I tried both netbeans and ant file deployment instructions are followed, but the same problem occurred -- config file is missing. I share the screenshot for that error. Please give me a solution for resolving the error.

Thanks in advance.

**Comment by vaughnte** [comment]
Go to blueseer/scripts directory and copy the bs.cfg into the blueseer/test directory.  This will use the sqlite database.   Then adjust your test/build.xml file to reflect your actual JDK path....see variable :
<property name="JDK17dir" location="/somepath/to/jdk" />.   
Then...go into blueseer/sf directory and copy entire data directory into blueseer/test .    
Then try running 'ant run'.
If you are using the netbeans approach....you need to do similar actions.   Copy bs.cfg and data directory into execution directory of your netbeans project.   
This initial how-to compile was written for windows...hence the .bat file....I will create a .sh script for it as well.

**Comment by iswaryalakshmim** [comment]
Thanks for your response sir,

I have followed by the above instructions but i am unable to deploy the project because the error displayed - unable to connect database 

![Screenshot from 2022-07-02 12-05-35](https://user-images.githubusercontent.com/108528009/176989726-9143aeb6-1858-4a2e-8254-a298d7fe7f6b.png)

herewith i am sharing the screenshot for that error. Please help to resolve the error sir .

Thanking you.

**Comment by vaughnte** [comment]
Make sure the complete data directory is in the test execution directory.   You should have a directory structure like test/data ...with a file in the directory like so:  test/data/bsdb.db .   It looks like your app is unable to see the database file "bsdb.db".   If this doesn't resolve it, send me an email to support@blueseer.com...and we can troubleshoot your error instance further.

**Comment by iswaryalakshmim** [comment]
Good Evening Sir,

I have followed by your instructions similarly ensure all the directory and
files sir but i am unable to run the project using ant and netbeans
approach sir. I am trying to resolve the error but couldn't sir. Herewith i
am sharing the screenshot for your reference sir.

Thank you sir

**Comment by vaughnte** [comment]
Send an email to support@blueseer.com and we will continue troubleshooting via email.

**Comment by iswaryalakshmim** [comment]
> Send an email to [support@blueseer.com](mailto:support@blueseer.com) with image of test directory and data directory contents within test/data....and we will continue troubleshooting via email.

![Screenshot from 2022-07-03 19-25-55](https://user-images.githubusercontent.com/108528009/177043076-ff9d55c6-59f6-4ce6-95d0-98a5764e74e8.png)
![Screenshot from 2022-07-03 19-26-16](https://user-images.githubusercontent.com/108528009/177043080-70574bd4-46ac-429b-8b17-9d7fa946e4ce.png)


Herewith i have attached test and data directory sir.

**Comment by vaughnte** [comment]
I think the problem is in the bs.cfg....the directory structure DB=data/en/bsdb.db .   I gave you the wrong bs.cfg to copy.   Your bs.cfg probably has windows dir structure...DB=data\en\bsdb.db.     My bad.   Copy over the blueseer/scripts/bs.cfg.sqlite.linux file into your test directory and rename it to bs.cfg.   That should do the trick.

**Comment by iswaryalakshmim** [comment]
Thankyou so much sir. Project successfully deployed.

**Comment by vaughnte** [comment]
Good to hear!   Enjoy.    Note:  I have added a refresh.sh script to the repository as well that basically does what we did manually.

**Comment by iswaryalakshmim** [comment]
Sure sir. Thankyou

**Comment by vaughnte** [comment]
resolved procedurally....added script for automation.
