### ISSUE TITLE
Order load by CSV file unresponsive 

### ISSUE THREAD

**Issue by sudocake** [blueseerERP/blueseer#68]
I'm just getting into Blueseer and so far I'm quite impressed with the software. One thing that I was excited to see was the "Order load by CSV" entry in the Order menu. Unfortunately, when I click this nothing happens. Should this be functioning or is it just a dead menu item? 

Basically, I'm looking for an easy way to load orders using a CSV file. I've thought about using the built-in EDI function for this, but I use Shopify for eCommerce and it's effortless to schedule a CSV drop off using their utilities.

**Comment by vaughnte** [comment]
That menu is indeed a dead menu....it should have been removed when I deprecated the menu class last version.   The old class wasn't generic enough to keep around...and was used for a special case.   However, if the shopify csv file is 'generic' to shopify carts...I might be willing to revisit this menu.   If you would like to send me a sample csv file (with column names), I'll take a look at it and see if it's worthwhile to resurrect the menu class.    Send a sample file to support@blueseer.com .

**Comment by sudocake** [comment]
Yes, the Shopify export has a generic format. I will send you a sample file. Thanks for considering this as a possible enhancement. There are a lot of Shopify users that could benefit from Blueseer. The ability to create BOMs and track raw material inventory are elements that are missing from standard Shopify.

**Comment by vaughnte** [comment]
Added two methods to load Shopify Orders (Draft and Fullfillment) into BlueSeer using the Master Data import routine.   This is now included in the release of Version 6.3.    Closing.
