### ISSUE TITLE
Custom font size

### ISSUE THREAD

**Issue by VedVid** [blueseerERP/blueseer#8]
Hello,

I'm currently looking for free ERP system for small company. BlueSeer looks promising, and I like that's not web-based solution.
Yet, I'm a little bit visually impaired, and the default font is not large enough for me to comfortably use BlueSeer.
Is it possible to enlarge font without recompiling sources?

Best regards
Ved

**Comment by vaughnte** [comment]
Given that it's a desktop application, your best approach may be to change the screen resolution to maximize the app without diminishing it's layout...i.e. excessive scrolling.   You do not have to recompile from source to do this.
