### ISSUE TITLE
Error while importing Data

### ISSUE THREAD

**Issue by jagroop77** [blueseerERP/blueseer#95]
We are trying to import the data from the colon seprated text file but for sum items it is showing error"must be valid routing code"
we tried loading the file by deleting the item on which error is showing but the error shifts to new line

Please help us.

**Comment by vaughnte** [comment]
If you're trying to load the itemmstr.txt file in the "sampledir', you need to load the Routings (routing.txt) first.   The files in the sample dir or a packaged deal....they all load in the required order when you click the "Test Data Load" button.   However, if you're just testing the item master load only...then you can check the 'data integrity override' checkbox, and it will load without validating the existence of the routing.   Also, if you are loading your own item master data, then you can leave the last field blank...which is the routing field "it_wf"...and it will load also.   If you have any further issues, send me your load file and I will research from there.  You can send it to support@blueseer.com.

**Comment by vaughnte** [comment]
Answered
